[10:27 PM] Willy Wijaya

name: Super-Linter

 

on: push

 

jobs:

  super-lint:

    name: Lint code base

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2


        env:

          DEFAULT_BRANCH: main
